kind: pipeline
name: default

steps:
  - name: test
    image: node:10-alpine
    commands:
      - npm install
      # - npm run test
    when:
    branch:
      - master
    event:
      - push
      - pull-request

  - name: deploy
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      NODE_ENV:
        from_secret: NODE_ENV      
      DB_HOST:
        from_secret: DB_HOST
      DB_PORT:
        from_secret: DB_PORT
      DB_USER:
        from_secret: DB_USER
      DB_PASS:
        from_secret: DB_PASS
      DB_DATABASE:
        from_secret: DB_DATABASE
      DB_1C_USER:
        from_secret: DB_1C_USER
      DB_1C_PASS:
        from_secret: DB_1C_PASS
      DB_1C_SERVER:
        from_secret: DB_1C_SERVER
      DB_1C_DATABASE:
        from_secret: DB_1C_DATABASE
      DB_1C_DATABASE_PROF:
        from_secret: DB_1C_DATABASE_PROF
      SSL_PASS:
        from_secret: SSL_PASS
      PORT: 8451
    settings:
      build_args_from_env:
      - NODE_ENV
      - PORT
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_DATABASE
      - DB_1C_USER
      - DB_1C_PASS
      - DB_1C_SERVER
      - DB_1C_DATABASE
      - DB_1C_DATABASE_PROF   
      - SSL_PASS
    commands:
      - docker build -t nick/marks_service .
      - docker rmi -f $(docker images -f "dangling=true" -q) || true
      - docker container stop marks_service || true && docker rm marks_service || true
      - docker run -v /home/marks_service_logs:/home/node/marks_service/logs -v /home/ssl:/home/node/marks_service/ssl -e NODE_ENV=$NODE_ENV -e DB_USER=$DB_USER -e DB_PASS=$DB_PASS -e DB_SERVER=$DB_SERVER -e DB_DATABASE=$DB_DATABASE -e DB_1C_USER=$DB_1C_USER -e DB_1C_PASS=$DB_1C_PASS -e DB_1C_SERVER=$DB_1C_SERVER -e DB_1C_DATABASE=$DB_1C_DATABASE -e DB_1C_DATABASE_PROF=$DB_1C_DATABASE_PROF -p 8451:8451 -d --net="host" --restart="always" --name=marks_service nick/marks_service
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: telegram
    image: appleboy/drone-telegram:latest
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_user_id
      message: >
      format: html
      message: >
        {{#success build.status}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a> 
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{else}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{/success}}
    when:
      status: [success, failure]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock